# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: windows-latest

steps:
# Cài .NET SDK
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '7.0.x'

# Restore solution
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'DistributedSystem.sln'

# Build solution
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'DistributedSystem.sln'
    arguments: '--configuration $(buildConfiguration)'

# Publish Web API project
- task: DotNetCoreCLI@2
  displayName: 'Publish Web API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/DistributedSystem.API/DistributedSystem.API.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# Upload artifact để deploy
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

# Deploy lên Azure App Service

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(5dd8c1c0-7f38-4954-90cc-5b3de6961ae3)'
    appType: 'webAppLinux'
    appName: 'command-api'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'