﻿apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-api-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: command-api-kubenetes
  template:
    metadata:
      labels:
        app: command-api-kubenetes
    spec:
      hostAliases:
      - ip: "192.168.1.4"
        hostnames:
        - "host.k8s.internal"
      containers:
      - name: command-api
        image: tuankhoa2009/command-api:v1
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:80"
        - name: ConnectionStrings__ConnectionStrings
          value: "Data Source=192.168.1.4,1435;Initial Catalog=DistributedSystemDatabase;User id=sa;Password=P@ssword; TrustServerCertificate=True"  
        - name: ConnectionStrings__Redis
          value: "192.168.1.4:6379"
        - name: JwtOption__Issuer
          value: "http://192.168.1.4:6000"
        - name: JwtOption__Audience
          value: "http://192.168.1.4:6000"
        - name: JwtOption__SecretKey
          value: "oEZqUKrrKDKP7A9OtrB4GfPGJ92vLDpK"
        - name: JwtOption__ExpireMin
          value: "5"
        - name: MasstransitConfiguration__Host
          value: "amqp://guest:guest@192.168.1.4:5672"
        - name: MasstransitConfiguration__VHost
          value: "/"
        - name: MasstransitConfiguration__Port
          value: "5672"
        - name: MasstransitConfiguration__UserName
          value: "guest"
        - name: MasstransitConfiguration__Password
          value: "guest"
        - name: MessageBusOptions__retryLimit
          value: "3"
        - name: MessageBusOptions__initialInterval
          value: "00:00:05"
        - name: MessageBusOptions__intervalIncrement
          value: "00:00:10"
---
apiVersion: v1
kind: Service
metadata:
  name: command-api-service
spec:
  type: NodePort  
  selector:
    app: command-api-kubenetes
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
